const Types = {
  SEND_CARETAKER_REQUEST: 'SEND_REQUEST_TO SEND_CARETAKER_REQUEST',
  SUCCESS_CARETAKER_REQUEST: 'SEND_REQUEST_TO_SEND_CARETAKER_REQUEST_SUCCESS',
  FAILED_CARETAKER_REQUEST: 'SEND_REQUEST_TO_SEND_CARETAKER_REQUEST_FAILED',
  
  GET_MED_IMAGES: 'SEND_REQUEST_TO_GET_MED_IMAGES',
  SUCCESS_MED_IMAGES: 'SEND_REQUEST_TO_GET_MED_IMAGES_SUCCESS',
  FAILED_MED_IMAGES: 'SEND_REQUEST_TO_GET_MED_IMAGES_FAILED',

  SEND_EMAIL: 'SEND_REQUEST_TO_SEND_EMAIL',
  SUCCESS_SEND_EMAIL: 'SEND_REQUEST_TO_SEND_EMAIL_SUCSESS',
  FAILED_SEND_EMAIL: 'SEND_REQUEST_TO_SEND_EMAIL_FAILED',

  GET_CARETAKERS: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST',
  Success_CareTAKER_REQUEST: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST_SUCCESS',
  Failed_CareTAKER_REQUEST: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST_FAILED',

  GET_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES',
  SUCCES_GET_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES_SUCCESS',
  FAILED_GET_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES_FAILED',
  
  GET_PROFILE:'SEND_REQUEST_TO_GET_PROFILE',
  SUCCESS_GET_PROFILE:'SEND_REQUEST_TO_GET_PROFILE',
  FAILED_GET_PROFILE:'SEND_REQUEST_TO_GET_PROFILE',

  GET_PATIENTS:'SEND_REQUEST_TO_GET_PATIENTS',
  SUCCESS_GET_PATIENTS:'SEND_REQUEST_TO_GET_PATIENTS',
  FAILED_TO_GET_PATIENTS:'SEND_REQUEST_TO_GET_PATIENT',

  SEND_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES',
  SUCCES_SEND_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES_SUCCESS',
  FAILED_SEND_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES_FAILED',

  GET_SEND_PDF:'SEND_REQUEST_TO_GET_PDF',
  SUCCESS_SEND_PDF:'SEND_REQUEST_TO_GET_PDF_SUCCESS',
  FAILED_SEND_PDF:'SEND_REQUEST_TO_PDF_FAILED',

  GET_USER:'SEND_REQUEST_TO_GET_USER_BY_EMAIL',
  SUCCESS_GET_USER:'SEND_REQUEST_TO_GET_USER_SUCCESS',
  FAILED_GET_USER:'SEND_REQUEST_TO_GET_USER_FAILED',

  LOGIN_REQUEST:'SEND_REQUEST_TO_GET_USER_LOGIN',
  SUCCESS_LOGIN:'SEND_REQUEST_TO_GET_USER_LOGIN_SUCCESS',
  FAILED_LOGIN:'SEND_REQUEST_TO_GET_USER_LOGIN_FAILED',

  GET_MEDICENE_HISTORY:'SEND_MEDICENE_HISTORY',
  SUCCESS_MEDICINE_HISTORY:'SEND_MEDICINE_HISTORY_SUCCESS',
  FAILED_MEDICINE_HISTORY:'SEND_MEDICINE_HISTORY_FAILED',

  GET_NETWORK_REQUEST:'SEND_NETWORK_REQUEST',
  SUCCESS_NETWORK_REQUEST:'SEND_NETWORK_REQUEST_SUCCESS',
  FAILED_NETWORK_REQUEST:'SEND_NETWORK_REQUEST_FAILED',

  GET_PATIENT_REQUEST:'SEND_PATIENT_REQUEST',
  SUCCESS_GET_PATIENT_REQUEST:'SEND_PATIENT_REQUEST_SUCCESS',
  FAILED_GET_PATIENT_REQUEST:'SEND_PATIENT_RAEQUEST_FAILED',

  GET_DELETE_PATIENT_REQUEST:'SEND_DELETE_PATIENT_REQUEST',
  SUCCESS_GET_DELETE_PATIENT_REQUEST:'SEND_DELETE_PATIENT_REQUEST_SUCCESS',
  FAILED_GET_DELETE_PATIENT_REQUEST:'SEND_DELETE_PATIENT_RAEQUEST_FAILED',

  PUT_ACCEPT_REQUEST:'PUT_ACCEPT_REQUEST',
  SUCCESS_ACCEPT_REQUEST:'PUT_ACCEPT_REQUEST_SUCCESS',
  FAILED_ACCEPT_REQUEST:'PUT_PATIENT_REQUEST_FAILED',
  
  PUT_UPDATE_USER_DETAILS:'PUT_UPDATE_USER_DETAILS',
  SUCCESS_UPDATE_USER_DETAILS:'PUT_UPDATE_USER_DETAILS_SUCCESS',
  FAILED_UPDATE_USER_DETAILS:'PUT_UPDATE_USER_DETAILS_FAILED',

  POST_SYNC_HISTORY:'POST_SYNC_HISTORY',
  SUCCESS_SYNC_HISTORY:'POST_SYNC_HISTORY_SUCCESS',
  FAILED_SYNC_HISTORY:'POST_SYNC_HISTORY_FAILED',

  POST_SYNC_DATA:'POST_SYNC_DATA',
  SUCCESS_SYNC_DATA:'POST_SYNC_DATA_SUCCESS',
  FAILED_SYNC_DATA:'POST_SYNC_DATA_FAILED',

  POST_SAVE_USER:'POST_SAVE_USER_DETAILS',
  SUCCESS_SAVE_USER:'POST_SAVE_USER_SUCCESS',
  FAILED_SAVE_USER:'POST_SAVE_USER_FAILED',

  GET_USER_BY_ID_REQUEST:'SEND_USER_BY_ID_REQUEST',
  SUCCESS_GET_USER_BY_ID_REQUEST:'SEND_USER_BY_ID_SUCCESS',
  FAILED_GET_USER_BY_ID_REQUEST:'SEND_USER_BY_ID_FAILED',

  SIGNUP_REQUEST: 'SEND_REQUEST_TO_SIGNUP',
  SUCCESS_SIGNUP: 'SEND_REQUEST_SIGNUP_SUCCESS',
  FAILED_SIGNUP: 'SEND_REQUEST_SIGNUP_FAILED',

  NOTIFY_PATIENT: 'SEND_REQUEST_TO_NOTIFY_PATIENT',
  SUCCESS_NOTIFY_PATIENT: 'SEND_REQUEST_TO_NOTIFY_PATIENT_SUCCESS',
  FAILED_NOTIFY_PATIENT: 'SEND_REQUEST_TO_NOTIFY_PATIENT_FAILED',

  GET_PATIENT: 'SEND_REQUEST_TO_GET_PATIENT',
  SUCCES_PATIENT: 'SEND_REQUEST_TO_GET_PATIENT_SUCCESS',
  FAILED_PATIENT: 'SEND_REQUEST_TO_GET_PATIENT_FAILED',
   
  GET_PATIENT_DETAILS: 'SEND_REQUEST_TO_GET_PATIENT_DETAILS',
  SUCCES_PATIENT_DETAILS: 'SEND_REQUEST_TO_GET_PATIENT_DETAILS_SUCCESS',
  FAILED_PATIENT_DETAILS: 'SEND_REQUEST_TO_GET_PATIENT_DETAILS_FAILED',

  SAVE_PROFILE: 'SEND_REQUEST_TO_SAVE_PROFILE_DETAILS',
  SUCCESS_PROFILE: 'SEND_REQUEST_TO_SAVE_PROFILE_SUCCESS',
  FAILED_PROFILE: 'SEND_REQUEST_TO_SAVE_PROFILE_FAILED',
};

export default Types;
